### ISSUE TITLE
read.csv in R

### ISSUE THREAD

**Issue by DeveauP** [sysbio-curie/ACSN_Enrichment#2]
The issue is the following:
http://stackoverflow.com/questions/18922493/how-can-you-read-a-csv-file-in-r-with-different-number-of-columns

As stated, read.csv only uses the first 5 lines to determine the number of columns... Hence the issue. I'll dig into that and correct the import code.

**Comment by erbon7** [comment]
A quick search pointed to a R function called 'readLines', might help to
solve the problem..

2015-10-09 13:42 GMT+02:00 Paul Deveau notifications@github.com:

**Comment by DeveauP** [comment]
Issue solved and pushed.
