### ISSUE TITLE
install_github failed

### ISSUE THREAD

**Issue by erbon7** [sysbio-curie/ACSN_Enrichment#3]
> library(devtools)
> Message d'avis :
> le package ‘devtools’ a été compilé avec la version R 3.1.3 
> install_github('sysbio-curie/ACSN_Enrichment')
> Downloading github repo sysbio-curie/ACSN_Enrichment@master
> Installing ACSN_Enrichment
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
>   --no-save --no-restore CMD INSTALL  \
>   '/private/var/folders/7l/0rp_x4dd74n4hv3hl1m6rrbw0000gr/T/RtmpCGyZAS/devtools103414d08f71/sysbio-curie-ACSN_Enrichment-b9e9909'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
>   --install-tests 
- installing _source_ package ‘ACSN_Enrichment’ ...
  Error : Fichier DESCRIPTION incorrect

Nom de package mal orthographié

Voyez l'information à propos des fichiers DESCRIPTION dans la section
'Creating R packages' du manuel 'Writing R Extensions'.

ERROR: installing package DESCRIPTION failed for package ‘ACSN_Enrichment’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ACSN_Enrichment’
  Erreur : Command failed (1)

**Comment by DeveauP** [comment]
There are 2 issues in fact: ACSN_Enrichment is not a valid package name due to the underscore. So we should move the package to another folder named ACSNEnrichment (if we keep this name)
